### ISSUE TITLE
Botão para alterar o tema | Button for changing theme

### ISSUE THREAD

**Issue by sam-chami** [matheusfelipeog/calculadora-tk#9]
Olá, estou trabalhando em um botão que altera o tema da calculadora, mas não sei como alterar o tema, pois
`self.style = style.White()` 
parece fazê-lo apenas no início. Se você pudesse me ajudar, ficaria muito grato.

![demo_estilo](https://user-images.githubusercontent.com/61357388/87873060-71e4a300-c9be-11ea-93c2-fd0b23230c40.gif)

**Comment by matheusfelipeog** [comment]
Perfeito, @sam-chami 👍 

## Problemas

A definição do tema e demais configurações são feitas na inicialização realmente, como você mencionou. Então, inicialmente, pensei que para realizar a troca de tema seria simplemente realizar uma nova instância de um dos objetos de estilo em tempo de execução, semelhante o fluxo seguinte: 

1. Usuário abre a calculadora, tema padrão é iniciado.
2. Usuário clica no botão para alterar tema.
3. O atributo `self.style` é alterado em tempo de execução por um método interno.
Exemplo:
```python
class Calculadora(object):
        def __init__(self, master):
(...)
            self.__ALTERA_ESTILO = tk.Button(master, text='', cnf=self.style.BTN_OPERADOR)

            self.__ALTERA_ESTILO['command'] = self.__altera_style

      def altera_style(self):
          self.style = style.White()
(...)
```
Ai o atributo `self.style` é alterado e a calculadora mudaria seu tema? Não! Não acontece isso.

Aparentemente, isso só funcionária caso estivesse manipulando um único *widget*, mas como são diversos *widget* (botões, inputs, frames, cores dos caracteres etc) que são configurados na inicialização, será necessário reiniciar o objeto da calculadora para fazer essa troca. 

Existe 2 métodos que fazem o trabalho de atualizar *widget's* que foram alterados em tempo de execução, como [`update()`](http://effbot.org/tkinterbook/widget.htm#Tkinter.Widget.update-method) e [`update_idletasks()`](http://effbot.org/tkinterbook/widget.htm#Tkinter.Widget.update_idletasks-method), ambos fazem com que eventos em espera no `mainloop` sejam executados. Você pode ver uma explicação sobre a diferença de ambos [AQUI](https://stackoverflow.com/questions/29158811/whats-the-difference-between-update-and-update-idletasks)

 Mas, novamente, por conta de ser diversos *widget's* alterados no mesmo momento, seria necessário reiniciar para que ocorresse uma re-definição do atributo `self.style`.

Fora os problemas descritos acima, ainda existe outro. 

Caso a realização da troca de tema funcionasse como descrito acima, o tema escolhido seria aplicado somente na sessão atual da calculadora, então sempre que o usuário fechar e executar a calculadora novamente, o estilo padrão, `Dark()`, seria inicializado novamente, assim perdendo o estilo selecionado anteriormente pelo usuário. E isso ocorre por que não existe um meio para mantermos as configurações do usuário armazenadas para ser inicializadas em uma próxima sessão.

## Soluções

Dito isso, vamos as possíveis soluções os problemas descritos.

### Armazenamento

Como descrevi, não é feito o armazenamento das configurações feitas pelo usuário, então precisamos implementar uma.

Atualmente, essas configurações são feitas a partir do arquivo [`./app/style.py`](https://github.com/matheusfelipeog/calculadora-tk/blob/master/app/style.py), sendo mantidas em classes. Que tal excluirmos esse arquivo e reestruturar todas as configurações em um arquivo `.json`, algo como `./app/settings.json`?

O arquivo ficaria mais ou menos nesse formato:

```
{
    "current_style": "Dark",
    
    "styles": [
        {
            "name": "Dark",
            
            "master_bg": "#252729",
            "frame_bg": "#252729",

            "INPUT": {
                "bg": "#252729",
                "fg": "white",
                "borderwidth": 0,
                "highlightthickness": 0,
                "width": 15,
                "font": "Arial 28 bold",
                "justify": "right"
            },

            "BTN_DEFAULT": {
                "bg": "#0e0f0f",
                "fg": "#f5f6fa",
                "activebackground": "#635f5f",
                "activeforeground": "#000000",
                "borderwidth": 0,
                "highlightthickness": 0,
                "width": 6,
                "height": 2,
                "font": "Arial 14 bold"
            },

            "BTN_NUMERICO": {
                "bg": "#050505",
                "fg": "#f5f6fa",
                "activebackground": "#635f5f",
                "activeforeground": "#000000",
                "borderwidth": 0,
                "highlightthickness": 0,
                "width": 6,
                "height": 2,
                "font": "Arial 14 bold"
            },

            "BTN_OPERADOR": {
                "bg": "#0e0f0f",
                "fg": "#f5f6fa",
                "activebackground": "#0097e6",
                "activeforeground": "#000000",
                "borderwidth": 0,
                "highlightthickness": 0,
                "width": 6,
                "height": 2,
                "font": "Arial 14 bold"
            },

            "BTN_CLEAR": {
                "bg": "#0e0f0f",
                "fg": "#f5f6fa",
                "activebackground": "#d63031",
                "activeforeground": "#000000",
                "borderwidth": 0,
                "highlightthickness": 0,
                "width": 6,
                "height": 2,
                "font": "Arial 14 bold"
            }
        },

       {...},

       {...}
    ]
}
```

E se você for atento aos detalhes, notará que existe uma certa repetição desnecessária de algumas configurações, já que elas são as mesmas para todos temas, exceto o do botão input, que são: `borderwidth`, `highlightthickness`, `width`, `height` e `font`. Podendo ser armazenadas em um único espaço generalizando para todos os temas:
```
{
    "current_style": "Dark",

    "global_settings": {
            "borderwidth": 0,
            "highlightthickness": 0,
            "width": 6,
            "height": 2,
            "font": "Arial 14 bold"
    },
    
    "styles": [
        {
            "name": "Dark",
            ...
    ]
}
```

Isso resolve o problema de armazenar as configurações feitas pelo usuário, assim, as mantendo para uma próxima sessão. 

**O que acha dessa solução para o armazenamento?**

### Inicialização e Troca de tema

Indo para o problema inicial, a troca de temas, tendo agora onde manter as configurações feitas pelo usuário no arquivo `settings.json`, podemos seguir o seguinte fluxo inicial:

1. Usuário abre a calculadora, tema padrão é iniciado, dado a esse exemplo de código implementado no lugar da definição de tema anterior:
```python

# Somente um exemplo, podendo sofrer alterações

class Calculadora(object):
        def __init__(self, master):
(...)
           self.current_style =  self._get_current_style()

            if platform.system() == 'Darwin':
                 self.style =  self._get_settings(name=current_style)
            else:
                 self.style =  self._get_settings(name=current_style)

       def _load_settings(self):
           """Carrega o arquivo settings.json na memória."""

       def _get_current_style(self):
           """Recupera somente o current_style utilizando _load_settings."""

       def _get_settings(self, name):
           """Recupera as configurações com base no valor recuperado de __get_current_style."""
(...)
```
2. É aberto, em modo leitura, o arquivo `settings.json`;
3. É recuperado a chave-valor `current_style` (que inicialmente estará como: `"current_style": "Dark"`;
4. Será feito a busca do `current_style` dentro da lista de `styles` no próprio arquivo;
5. E por fim, as configurações recuperadas na lista com base no `current_style` são carregadas e a calculadora é estilizada e configurada.

> OBS: Seguindo esse processo, será necessário alterar todos os locais onde existe uma chamada a `self.style.(INPUT, BTN_NUMERICO, BTN_DEFAULT, BTN_OPERADOR e BTN_CLEAR)` ou procedimento semelhante . Já que não existe mais esses atributos em `self.style` e sim dicionários. Exemplo de chamada: `self.style['INPUT']`

Agora, para a troca do tema em si, precisamos editar editar o arquivo `settings.json` e trocar o valor de `current_style` para o tema escolhido pelo usuário. E, novamente, aqui temos o problema descrito no inicio do texto, que é a atualização de varios *widget's* em tempo de execução. Para resolver isso, bastaria reiniciar a calculadora e o novo tema seria carregado como padrão. Então sempre que o usuário fechar e abrir novamente, as configurações feitas na última sessão estará salva e vão ser carregadas para nova sessão. 😄 

Para reiniciar a calculadora como descrevi, encontrei [esse problema no StackOverFlow](https://stackoverflow.com/questions/41655618/restart-program-tkinter) que achei bem interessante e resolve o problema.

Então, no click do usuário em outro tema, depois de todo processo de alteração do arquivo `settings.json`, só é necessário chamar um método interno que reinicia a calculadora, como: `self._realod_app()` ou o que achar melhor.
Exemplo:
```python
import sys
import os
(...)

class Calculadora(object):
(...)

     def _realod_app(self):
         """Reinicia o aplicativo para subir novas configurações."""
         python = sys.executable  # Recupera o path do executável do python
         os.execl(python, python, * sys.argv)

    def _edit_current_style(self, new_style):
        ...
        self._realod_app()
(...)
```

Acredito que isso já resolveria todo o problema que você descreveu e os que eu encontrei. 😄 

### Dicas

Notei que você utilizou um dos botões dentro do escopo de funcionalidades da calculadora para alterar o estilo, invés de usar desse modo, use uma barra de menu superior com uma aba `configurações` > `temas`, que tal? Assim mantem somente funcionalidades dentro do escopo de funcionalidades. 

Fica mais ou menos assim, por exemplo:

![image](https://user-images.githubusercontent.com/50463866/88078672-1a2b7080-cb53-11ea-933b-4bec59fd038b.png)

Caso não saiba como implementar isso, de uma olhada nessa documentação [AQUI](https://tkdocs.com/tutorial/menus.html). Nela explica como você pode implementar os menus e suas funcionalidades.

### Finalizando

Perdão por ter escrito algo tão longo, mas achei necessário para matar todas suas duvidas e possíveis problemas que poderiam acontecer. Espero que tenha sido bem sucedido nisso.

**Caso você queira ou não implementar** a parte do **Armazenamento**, me informe aqui, por favor. Porque, caso você não queira implementar essa parte, eu mesmo implemento e você só ficará com a parte de **Troca de Tema**. O único problema é que teria que esperar pela minha atualização para você continuar seu trabalho. 😆 

Qualquer duvida que tiver, venha novamente aqui e a descreva que vou ajuda-lo assim que possível. 👍

**Comment by matheusfelipeog** [comment]
@sam-chami, pode me informar se está trabalhando nessa feature?

**Comment by sam-chami** [comment]
Sim, o que acontece é que eu não sou muito veterano em Python. Vou pelo menos tentar adicionar o menu superior.

**Comment by matheusfelipeog** [comment]
Tudo bem, @sam-chami  😄 

Outra pessoa completa essa parte do ``settings.json``, ou eu mesmo. Assim, você pode terminar a sua implementação.

Qualquer dúvida que tiver, pode vir aqui perguntar. 👍

**Comment by matheusfelipeog** [comment]
@sam-chami, fiz a atualização base que descrevi antes. Agora você pode implementar, caso queira, toda parte do menu e suas funcionalidades sem problemas. Basta seguir o caminho que descrevi.

Pode ver as alterações [aqui](https://github.com/matheusfelipeog/calculadora-tk/commit/d87fc88592ad2c3921783576bd7d882c15c7cf2f).

**Comment by sam-chami** [comment]
Óla @matheusfelipeog, Não encerro o Issue, caso veja algo que possa ser melhorado. #10
